### ISSUE TITLE
unicodes are wrong

### ISSUE THREAD

**Issue by JakobJingleheimer** [gustavohenke/webhostinghub-glyphs#6]
The unicodes in your css files are wrong.

Yours

``` css
.icon-fatredo:before {
    content: '\e19e';
}
```

Theirs

``` css
.icon-fatredo:before {
    content: '\f692';
}
```
